apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  labels:
    app.kubernetes.io/instance: spring
resources:
  - namespace.yaml
  - spring.yaml

configMapGenerator:
  - name: spring-config
    namespace: spring
    files:
      - config/application-cloud.yaml

secretGenerator:
  - name: spring-secret
    namespace: spring
    files:
      - secret/secret-cloud.yaml
  - name: registry-credential
    namespace: spring
    files:
      - .dockerconfigjson=secret/registry.json
    type: kubernetes.io/dockerconfigjson
    options:
      disableNameSuffixHash: true
