version: '3.5'
services:
  postgresql:
    image: bitnami/postgresql:15.2.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
      - './config/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql'

volumes:
  postgresql_data:
    driver: local
