apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  labels:
    app.kubernetes.io/instance: spring
resources:
  - namespace.yaml
  - cert-manager.yaml
  - selfsigned-issuer.yaml
  - certificate.yaml
