apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - service-account.yaml

secretGenerator:
  - name: registry-credential
    namespace: stacktic
    files:
      - .dockerconfigjson=secret/registry.json
    type: kubernetes.io/dockerconfigjson

generatorOptions:
  disableNameSuffixHash: true
