auth:
  existingSecret: "postgresql-admin-password"
  database: postgres
primary:
  initdb:
    scriptsSecret: "postgresql-initdb"

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: prometheus
    interval: 15s
    relabelings:
      - targetLabel: instance
        replacement: postgresql
